#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : padaos
Version  : 0.1.9
Release  : 6
URL      : https://files.pythonhosted.org/packages/5d/d9/f1e366c164c551c79e988c43fa282aea6e671d7842e6f70164ae09ad6376/padaos-0.1.9.tar.gz
Source0  : https://files.pythonhosted.org/packages/5d/d9/f1e366c164c551c79e988c43fa282aea6e671d7842e6f70164ae09ad6376/padaos-0.1.9.tar.gz
Summary  : A rigid, lightweight, dead-simple intent parser
Group    : Development/Tools
License  : MIT
Requires: padaos-python = %{version}-%{release}
Requires: padaos-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# Padaos
*A rigid, lightweight, dead-simple intent parser*
To deploy an intent parser into production with an automated feedback loop,
it's essential that the new data doesn't interfere with the old data. It's
also necessary that the parser can learn from sentences that closely match
written English (or any other language). That's what Padaos does.

%package python
Summary: python components for the padaos package.
Group: Default
Requires: padaos-python3 = %{version}-%{release}

%description python
python components for the padaos package.


%package python3
Summary: python3 components for the padaos package.
Group: Default
Requires: python3-core

%description python3
python3 components for the padaos package.


%prep
%setup -q -n padaos-0.1.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1548943343
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
